### ISSUE TITLE
Error on launch 

### ISSUE THREAD

**Issue by GDman1616** [Snaacky/Emerald#1]
When I run the code I get this error:

Traceback (most recent call last):
  File "C:/Users/Gürgün/Documents/PythonBible/untitled/noflash.py", line 2, in <module>
    import pymem
  File "C:\Users\Gürgün\venv\untitled1\lib\site-packages\pymem\__init__.py", line 7, in <module>
    import pymem.process
  File "C:\Users\Gürgün\venv\untitled1\lib\site-packages\pymem\process.py", line 5, in <module>
    from win32api import GetCurrentProcess
ImportError: DLL load failed: The specified module could not be found.
------------------
I have pymem and pywin32 installed but why do I get this error

**Comment by Snaacky** [comment]
For some reason I didn't get any notifications regarding issues on this repo:

But it definitely looks like you are/were missing the win32api for Python.
