### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by ghost** [Snaacky/Emerald#2]
C:\Users\Gürgün\venv\untitled1\Scripts\python.exe C:/Users/Gürgün/Documents/PythonBible/untitled/noflash.py
The token does not have the specified privilege. 
Traceback (most recent call last):
  File "C:\Users\Gürgün\venv\untitled1\lib\site-packages\pymem\__init__.py", line 246, in read_int

    value = pymem.memory.read_int(self.process_handle, address)
DarkFlashes has launched. Enable no-flash with x.
  File "C:\Users\Gürgün\venv\untitled1\lib\site-packages\pymem\memory.py", line 197, in read_int
    bytes = read_bytes(handle, address, struct.calcsize('i'))
  File "C:\Users\Gürgün\venv\untitled1\lib\site-packages\pymem\memory.py", line 82, in read_bytes
    raise pymem.exception.WinAPIError(error_code)
pymem.exception.WinAPIError: Windows api error, error_code: 1300

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Gürgün/Documents/PythonBible/untitled/noflash.py", line 35, in <module>
    main()
  File "C:/Users/Gürgün/Documents/PythonBible/untitled/noflash.py", line 14, in main
    flash_value = pm.read_int(player) + m_flFlashMaxAlpha
  File "C:\Users\Gürgün\venv\untitled1\lib\site-packages\pymem\__init__.py", line 248, in read_int
    raise pymem.exception.MemoryReadError(address, struct.calcsize('i'), e.error_code)
pymem.exception.MemoryReadError: Could not read memory at: 546111740, length: 4 - GetLastError: 1300

Process finished with exit code 1

**Comment by GDman1616** [comment]
I don't understand but there is just something wrong with pm.read_int(player) + something it always throws an error when I take that line it just works (of course I mean it just doesn't throw that error)

**Comment by Snaacky** [comment]
For some reason I didn't get any notifications regarding issues on this repo:

I'm almost positive the code works, not in the position to test it right now, but I don't think I broke anything before pushing it to the main branch. Did you update the offsets to ones matching the latest CS:GO version?
